---
- name: creating user and dir using varibale external "userlist" file
  hosts: all
  become: true
  vars_files:
   - /home/ansadmin/playbooks/userlist

  tasks:
  - name: Creating user {{user_name}}
    user:
     name: "{{user_name}}"
          
  - name: Creatiner directory for {{user_name}}
    file:
     path: /opt/{{user_name}}_temp_dir
     state: directory
     owner: "{{user_name}}"
     group: "{{user_name}}"
     mode: 0755
     
