---
- name: install multiple package
  hosts: all
  become: true

  tasks:
  - name: installing httpd & tree...
    yum:
     name: "{{item}}"
     state: installed
    with_items:
     - httpd
     - tree
     
